# Generated by Django 5.0.6 on 2024-07-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_issues', models.TextField()),
                ('blood_level', models.CharField(max_length=10)),
                ('place', models.TextField()),
                ('blood_group', models.CharField(max_length=3)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.user')),
            ],
            options={
                'db_table': 'donator',
            },
        ),
    ]
