# Generated by Django 5.0.6 on 2024-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_blooddonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
